-- BITMAPINDEX :

-- Create BitmapIndexDemo Table :

CREATE TABLE BitmapIndexDemo (
    ID INT GENERATED BY DEFAULT AS IDENTITY ,
    Active NUMBER NOT NULL ,
    PRIMARY KEY (ID)
);

-- And The Following Statement Creates A Bitmap Index On The Active Column :

CREATE BITMAP INDEX IndexBitampIndexDemoActive
ON BitmapIndexDemo (Active);

-- Open Two Sessions And Repeatedly Execute One Of The Following Statements In Each Session :

INSERT INTO BitmapIndexDemo (Active) VALUES(1);

INSERT INTO BitmapIndexDemo (Active) VALUES(0);